### ISSUE TITLE
Source separation models fail silently for audio with sample rate != 22050

### ISSUE THREAD

**Issue by rhine3** [kitzeslab/bioacoustics-model-zoo#7]
If you try to use one of the MixIT source separation models on a recording with a sample rate other than 22050, the model interprets the audio samples as if they have a sample rate of 22050

**Comment by sammlapp** [comment]
oof, we should definitely put resampling in the preprocessor. Thanks

**Comment by sammlapp** [comment]
issue was with defining sr of new audio, rather than resampling the input. Should be resolved.
